title: K9ine
description: 1.8.9 pvp client :)
logo: https://images.cdn4.stockunlimited.net/preview1300/canine-tooth_1442370.jpg
show_downloads: false
github:
  repository_url: https://github.com/Pragnyayadav/Project-K9ine
  discord_url: https://discord.gg/
cur_ver: 1.2
theme: jekyll-theme-cayman